### ISSUE TITLE
Revise PR template for trainees

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/CYF-Coursework-Template#1]
I've almost never seen this filled in, which suggests they are not finding it useful.

I really dislike training people into ignoring PR templates, which is what I think we are doing now. It's the sort of thing that can make our people look bad at work/ on projects. Can we revise this to be more useful?

I think the idea is to encourage formative self assessment, which is probably a good idea to try to do,  it's just that this isn't effective as it stands. Can we think how to make this more useful for everyone?

Would be great to get some advice from trainees here, as it's for them ultimately.

**Comment by SallyMcGrath** [comment]
Some suggested people to consult:

@CodeYourFuture/london-class-9 @CodeYourFuture/west-midlands-class-4

**Comment by SallyMcGrath** [comment]
Note, I have done a first revision just to remove some of the most unhelpful stuff and tagged at 2.0.0

**Comment by kfklein15** [comment]
@SallyMcGrath , can you link here the PR template we are considering for this ticket, please?

**Comment by kfklein15** [comment]
@SallyMcGrath , are we talking about the Syllabus PR only or some other PR? 
If possible can you link them on here, please?

**Comment by SallyMcGrath** [comment]
It's the PR template on this repo @kfklein15 (the CYF-Coursework-Template repo this ticket belongs to)

https://github.com/CodeYourFuture/CYF-Coursework-Template/blob/main/.github/pull_request_template.md


The previous version (the one currently being ignored by everyone on every repo made from this template) is here 

https://github.com/CodeYourFuture/CYF-Coursework-Template/blob/3abc5932714ae66c6895cec9c84d23e84857f0a9/.github/pull_request_template.md

**Comment by ShayanMahnam** [comment]
the new version will be more helpful as I can see. Well done 👏

**Comment by kfklein15** [comment]
@SallyMcGrath , the version you created is already simple and efficient. Have people started using it?

Question: is the information Module / Week not important?

**Comment by Grajales-K** [comment]
Hi Sally, Do we have to start to use this version template in every PR? because I received the notification by email, but I am not sure if we should start now or no? thank you.

**Comment by kfklein15** [comment]
Hi @Grajales-K , when you create a new PR, is it giving you the [new PR template](https://github.com/CodeYourFuture/CYF-Coursework-Template/blob/main/.github/pull_request_template.md) or some other?

**Comment by Grajales-K** [comment]
Hi, @kfklein15, for now, is still the old version.

**Comment by SallyMcGrath** [comment]
Someone needs to actually go and change them all - it's a piece of work. It's on @Dedekind561 's list!

**Comment by SallyMcGrath** [comment]
> @SallyMcGrath , the version you created is already simple and efficient. Have people started using it?
> 
> Question: is the information Module / Week not important?

The repo is already named by module and week so it's tautologous.
